export const LOAD_IDEAS_SUCCESS = 'LOAD_IDEAS_SUCCESS';
export const CREATE_IDEA_SUCCESS = 'CREATE_IDEA_SUCCESS';
export const UPDATE_IDEA_SUCCESS = 'UPDATE_IDEA_SUCCESS';
export const DELETE_IDEA_SUCCESS = 'DELETE_IDEA_SUCCESS';
